apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
      - name: gateway
        image: chokhareganesh/db_gateway:gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 8007
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "120Mi"
            cpu: "550m"
      imagePullSecrets:
      - name: private-secret
