apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  labels:
    name: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ui-service
  template:
    metadata:
      labels:
        name: ui-service
    spec:
      containers:
      - name: ui
        image: chokhareganesh/nodeapptwo:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "120Mi"
            cpu: "550m"

